const ROOT_FREQUENCY = 55;
const INSTRUMENT_AMOUNT = 2;
const SEQUENCE_AMOUNT = 4;
const SEQUENCE_LENGTH = 16;

export {
    ROOT_FREQUENCY,
    INSTRUMENT_AMOUNT,
    SEQUENCE_AMOUNT,
    SEQUENCE_LENGTH
}